trigger:
- master
pr:
  - master 
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: springpetcliniic

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17' 
    jdkArchitectureOption: 'x64' 
    jdkSourceOption: 'PreInstalled' 
  displayName: 'java 17 installed for azure'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-B'
    goals: 'clean package'
  displayName: 'Maven Compile'

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SONAR_CLOUD_1' 
    organization: '$(SONAR_ORGANIZATION)' 
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'     
    cliProjectName: '$(SONAR_PROJECT)'     
    cliProjectVersion: '1.0'
    extraProperties: |
      sonar.java.binaries=target/classes
      sonar.sources=src/main/java
      sonar.tests=src/test/java
      sonar.junit.reportPaths=target/surefire-reports
      sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  displayName: 'Prepare analysis on SonarCloud'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify sonar:sonar'
    options: '-Dsonar.cloud=$(SONAR_TOKEN)'
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'


- task: Docker@2
  inputs:
    containerRegistry: 'DOCKER_HUB'
    repository: 'kasinenichandu/spring-petclinic'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
